name: Update Anime DB

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # todo dia 03:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run updater
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python scripts/update_tmdb.py

      - name: Commit and push
        run: |
          git config user.name "anime-db-bot"
          git config user.email "bot@users.noreply.github.com"
          git add data/*.json
          git commit -m "Auto update anime catalog" || exit 0
          git push
